### PR TITLE
add some function to adjust juju/error

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
IsNotFound
NotValidf
IsAlreadyExists
AlreadyExistsf

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@gregwebs  PTAL

**Comment by gregwebs** [comment]
This is good from a compatibility perspective. However, I would like to move towards using the pkg/errors API and removing the need for the juju adapater if possible. That includes using structured errors rather than string matching.

pkg/errors has a function that can be used to [find a structured error type](https://github.com/pingcap/errors/blob/master/errors.go#L314) rather than just string matching.

[errcode](https://github.com/pingcap/errcode/blob/master/codes.go#L38) uses this and formalizes error types as error codes.

So I am also wondering which projects need this and if they can start to consider using proper error types.

But we can also merge this now and put off refactoring until later.

**Comment by WangXiangUSTC** [comment]
I agree with you, this is just a temporary solution, because I need use these function now, it is a little emergency, we can merge this now, and refine it later. @gregwebs

**Comment by gregwebs** [comment]
I think we should make the juju adapter be a separate package.

**Comment by WangXiangUSTC** [comment]
@gregwebs  please merge this pr, I am not authorized to do this, thanks!

**Comment by lysu** [comment]
LGTM... I don't jave permission too

**Comment by gregwebs** [comment]
merged. @lysu that's weird: you merged PRs in the past and I don't think permissions changed. I made you an admin if you want to look at the settings.

**Pull request merged**
